version: '3.8'

services:
  node-app:
    build: .
    container_name: node-api
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama-server
    ports:
      - '11434:11434'
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama-data:
